export const LOADING_STARTED = 'LOADING_STARTED';
export const LOADING_COMPLETED = 'LOADING_COMPLETED';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';
export const CLEAN_ERRORS = 'CLEAN_ERRORS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';

export const ADD_ORGANISATION = "ADD_ORGANISATION";
export const GET_ORGANISATION = "GET_ORGANISATION";
export const GET_ORGANISATIONS = "GET_ORGANISATIONS";
export const UPDATE_ORGANISATION = "UPDATE_ORGANISATION";
export const SELECT_ORGANISATION = "SELECT_ORGANISATION";
export const DESELECT_ORGANISATION = "DESELECT_ORGANISATION";
export const DELETE_ORGANISATION = "DELETE_ORGANISATION";

export const GET_USERS = 'GET_USERS';
export const POST_USER = 'POST_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SELECT_USER = 'SELECT_USER';
export const DESELECT_USER = 'DESELECT_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_COURSES='GET_COURSES';
export const CREATE_COURSE = 'CREATE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const SELECT_COURSE = 'SELECT_COURSE';
export const DESELECT_COURSE = 'DESELECT_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';